spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://arclight.space:1234/arclight?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: xxxx
    port: 1234
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 1234
  tomcat:
    uri-encoding: UTF-8

