spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://arclight.space:123/arclight?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: arclight.space
    port: 1233
    password: 123

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 123
  tomcat:
    uri-encoding: UTF-8

